Repository dockstore/dockstore, pull requests merged in 2019-04, with the labels that each got.

#2341 Separated out for-developer docs.
  README.md
  _data/docs.yml
  _docs/conversions.md
  _docs/developing-file-provisioning-plugins.md
  _docs/for-developers.md
  _docs/language-support.md
  _docs/set-up-file-provisioning-plugins.md
  _docs/ways-to-register-tools.md
  assets/images/docs/file-provisioning-plugins.png
Labels: documentation

#2363 fixed links in docs
  _docs/firecloud-launch-with.md
  _docs/terra-launch-with.md
  _posts/2017-05-05-Upcoming-Features.markdown
Labels: documentation

#2416 feature/2343/add orgs and collections to sitemap endpoint
  dockstore-webservice/src/main/java/io/dockstore/webservice/resources/MetadataResource.java
  dockstore-webservice/src/main/resources/openapi.yaml
  dockstore-webservice/src/main/resources/openapi3/openapi.yaml
  dockstore-webservice/src/main/resources/swagger.yaml
Labels: enhancement, web-service

#2423 Security update testing
  pom.xml
Labels: dependencies
