Repository dockstore/dockstore, pull requests merged in 2020-08, with the labels that each got.

#3708 Don't hide default versions and vice versa
  dockstore-integration-testing/src/test/java/io/dockstore/client/cli/GeneralIT.java
  dockstore-integration-testing/src/test/java/io/dockstore/client/cli/GeneralWorkflowIT.java
  dockstore-integration-testing/src/test/java/io/dockstore/client/cli/WorkflowIT.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/core/Entry.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/SourceCodeRepoInterface.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoTagResource.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/resources/WorkflowResource.java
  dockstore-webservice/src/main/resources/openapi3/openapi.yaml
  dockstore-webservice/src/main/resources/swagger.yaml
Labels: bug

#3699 Feature/3644/changes needed to ignore sourcefiles
  dockstore-integration-testing/src/test/java/io/dockstore/client/cli/BasicIT.java
  dockstore-integration-testing/src/test/java/io/dockstore/client/cli/GeneralIT.java
  dockstore-integration-testing/src/test/java/io/dockstore/client/cli/WorkflowIT.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/core/SourceFile.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/core/Version.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/core/database/VersionVerifiedPlatform.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoTagResource.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/resources/EntryResource.java
  dockstore-webservice/src/main/resources/openapi3/openapi.yaml
Labels: enhancement

#3755 update bom-internal pom
  bom-internal/pom.xml
  dockstore-webservice/src/main/resources/openapi3/openapi.yaml
Labels: bug

#3768 fix notification swagger
  THIRD-PARTY-LICENSES.txt
  dockstore-webservice/src/main/java/io/dockstore/webservice/resources/NotificationResource.java
  dockstore-webservice/src/main/resources/openapi3/openapi.yaml
  dockstore-webservice/src/main/resources/swagger.yaml
Labels: bug

#3762 update to admin, maintainer, and member organization user roles
  THIRD-PARTY-LICENSES.txt
  dockstore-integration-testing/src/test/java/io/dockstore/client/cli/OrganizationIT.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/core/OrganizationUser.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/resources/CollectionResource.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/resources/OrganizationResource.java
  dockstore-webservice/src/main/resources/migrations.1.9.0.xml
  dockstore-webservice/src/main/resources/openapi3/openapi.yaml
  dockstore-webservice/src/main/resources/swagger.yaml
Labels: enhancement

#3740 feature/3712/lazyLoadSourcefiles
  dockstore-integration-testing/src/test/java/io/dockstore/client/cli/CRUDClientIT.java
  dockstore-integration-testing/src/test/java/io/dockstore/client/cli/ExtendedNextflowIT.java
  dockstore-integration-testing/src/test/java/io/dockstore/client/cli/GeneralIT.java
  dockstore-integration-testing/src/test/java/io/dockstore/client/cli/GeneralWorkflowIT.java
  dockstore-integration-testing/src/test/java/io/dockstore/client/cli/WorkflowIT.java
  dockstore-integration-testing/src/test/java/io/dockstore/webservice/ServiceIT.java
  dockstore-integration-testing/src/test/java/io/dockstore/webservice/WebhookIT.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/DockstoreWebserviceApplication.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/core/SourceFile.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/core/Version.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/EntryVersionHelper.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/FileDAO.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/resources/AbstractHostedEntryResource.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoResource.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/resources/HostedToolResource.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/resources/HostedWorkflowResource.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/resources/WorkflowResource.java
  dockstore-webservice/src/main/java/io/openapi/api/impl/ToolsApiServiceImpl.java
  dockstore-webservice/src/main/resources/openapi3/openapi.yaml
Labels: enhancement

#3757 Feature/3741/fix hiding tool versions
  dockstore-webservice/src/main/java/io/dockstore/webservice/core/VersionMetadata.java
  dockstore-webservice/src/main/resources/openapi3/openapi.yaml
Labels: bug, gui, web-service
