Repository dockstore/dockstore, pull requests merged in 2021-09, with the labels that each got.

#4446 4407/collection display name bug fix
  dockstore-integration-testing/src/test/java/io/dockstore/client/cli/OrganizationIT.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/core/Collection.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/CollectionDAO.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/resources/CollectionResource.java
  dockstore-webservice/src/main/resources/import.sql
  dockstore-webservice/src/main/resources/migrations.1.12.0.xml
Labels: bug

#4471 require email
  dockstore-integration-testing/src/test/java/io/dockstore/client/cli/OrganizationIT.java
  dockstore-integration-testing/src/test/java/io/dockstore/client/cli/WorkflowIT.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/resources/OrganizationResource.java
Labels: enhancement

#4470 Fixed organization update to fail gracefully when no name specified
  dockstore-integration-testing/src/test/java/io/dockstore/client/cli/OrganizationIT.java
  dockstore-webservice/src/main/java/io/dockstore/webservice/resources/OrganizationResource.java
Labels: web-service
